#!/bin/bash

PROJECT_ID="web-page-d9ec622e"

echo "================================================"
echo "Manual OAuth2 Setup Instructions"
echo "================================================"
echo ""
echo "Since IAP OAuth clients don't work for regular Google Sign-In,"
echo "you need to manually create an OAuth2 client in the Google Cloud Console."
echo ""
echo "Step 1: Open the Google Cloud Console"
echo "---------------------------------------"
echo "Go to: https://console.cloud.google.com/apis/credentials/oauthclient?project=$PROJECT_ID"
echo ""
echo "Step 2: Configure OAuth Consent Screen (if not done)"
echo "-----------------------------------------------------"
echo "1. Go to OAuth consent screen tab"
echo "2. Choose 'External' for user type"
echo "3. Fill in:"
echo "   - App name: FatesBlind Portal"
echo "   - User support email: rbergman@fatesblind.com"
echo "   - App domain: https://fatesblind.com"
echo "   - Authorized domains: fatesblind.com"
echo "   - Developer contact: rbergman@fatesblind.com"
echo "4. Save and Continue"
echo "5. Skip Scopes (just click Save and Continue)"
echo "6. Add test users if needed, or publish the app"
echo ""
echo "Step 3: Create OAuth 2.0 Client ID"
echo "-----------------------------------"
echo "1. Click '+ CREATE CREDENTIALS' > 'OAuth client ID'"
echo "2. Application type: Web application"
echo "3. Name: FatesBlind Web Client"
echo "4. Authorized JavaScript origins - Add these URIs:"
echo "   - https://fatesblind.com"
echo "   - https://www.fatesblind.com"
echo "   - https://storage.googleapis.com"
echo "   - http://localhost:3000 (for testing)"
echo "   - http://localhost"
echo "5. Leave Authorized redirect URIs empty (not needed for Google Sign-In JS)"
echo "6. Click CREATE"
echo ""
echo "Step 4: Update Your Website"
echo "----------------------------"
echo "1. Copy the Client ID from the popup (format: XXXXXX.apps.googleusercontent.com)"
echo "2. Update index.html line 214 with the new Client ID"
echo ""
echo "Current (broken) IAP Client ID:"
echo "231662253958-lrvhdulmo2kpokvulhpas4odudou3ta4.apps.googleusercontent.com"
echo ""
echo "Replace it with your new OAuth2 Web Application Client ID"
echo ""
echo "================================================"
echo "Press Enter to open the Console in your browser..."
read

# Try to open the browser
if command -v xdg-open > /dev/null; then
    xdg-open "https://console.cloud.google.com/apis/credentials?project=$PROJECT_ID"
elif command -v open > /dev/null; then
    open "https://console.cloud.google.com/apis/credentials?project=$PROJECT_ID"
else
    echo "Please manually open: https://console.cloud.google.com/apis/credentials?project=$PROJECT_ID"
fi