runtime: nodejs20

env: standard

instance_class: F2

env_variables:
  NODE_ENV: production

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always
    expiration: "365d"

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
