name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
    paths:
      - 'nextjs-site/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: nextjs-site/package-lock.json

      - name: Install dependencies
        run: |
          cd nextjs-site
          npm ci

      - name: Build Next.js application
        run: |
          cd nextjs-site
          npm run build
        env:
          NODE_ENV: production

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to App Engine
        run: |
          cd nextjs-site
          gcloud app deploy app.yaml \
            --project=web-page-d9ec622e \
            --quiet \
            --version=v$(date +%Y%m%d%H%M%S)